---
- name: Install HTTP server
  hosts: g1
  become: yes
  tasks:
    - name: Install HTTPD
      yum:
        name: httpd
        state: present
      when: ansible_distribution == "Amazon"
    
    - name: Start httpd
      service:
        name: httpd
        state: started
      when: ansible_distribution == "Amazon"
    
    - name: Enable httpd
      service:
        name: httpd
        enabled: yes
      when: ansible_distribution == "Amazon"
    
    - name: Install Apache2
      apt:
        name: apache2
        state: present
      when: ansible_distribution == "Ubuntu"
    
    - name: start apache2
      service:
        name: apache2
        state: started
      when: ansible_distribution == "Ubuntu"
    
    - name: Enable Apache2
      service:
        name: apache2
        enabled: yes
      when: ansible_distribution == "Ubuntu"
    
    - name: Update apt cache on Debian
      apt:
        update_cache: yes
      when: ansible_distribution == "Debian"
    
    - name: Install Apache2 on Debian
      apt:
        name: apache2
        state: present
      when: ansible_distribution == "Debian"
    
    - name: start apache2 on Debian
      service:
        name: apache2
        state: started
      when: ansible_distribution == "Debian"
    
    - name: Enable Apache2 on Debian
      service:
        name: apache2
        enabled: yes
      when: ansible_distribution == "Debian"
...
